Web_cross_platform/Models/CommonDataModel.cs
namespace Web_cross_platform.Models
{
    public class CommonDataModel
    {
        public string Size { get; set; }
        public string Data { get; set; }

        public string ErrorValue { get; set; }
        public string Response { get; set; }
        public bool Calculated { get; set; }
    }
}

Web_cross_platform/Models/ErrorViewModel.cs
namespace Web_cross_platform.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web_cross_platform/Models/UserProfileModel.cs
namespace Web_cross_platform.Models
{
    public class UserProfileModel
    {
        public string UserName { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Web_cross_platform/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Okta.AspNetCore;
using Web_cross_platform.Models;

namespace Web_cross_platform.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            if (!HttpContext.User.Identity.IsAuthenticated)
            {
                return Challenge(OktaDefaults.MvcAuthenticationScheme);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult SignOut()
        {
            return new SignOutResult(
                new[]
                {
                    OktaDefaults.MvcAuthenticationScheme,
                    CookieAuthenticationDefaults.AuthenticationScheme,
                },
                new AuthenticationProperties { RedirectUri = "/Home/" });
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View(new UserProfileModel()
            {
                Email = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "email").Value.ToString(),
                FirstName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "given_name").Value.ToString(),
                LastName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "family_name").Value.ToString(),
                UserName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "preferred_username").Value.ToString(),
                PhoneNumber = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "phone_number")?.Value.ToString()
            });
        }

    }
}

Web_cross_platform/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web_cross_platform.Models;

namespace Web_cross_platform.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web_cross_platform/Controllers/LabsController.cs
using Microsoft.AspNetCore.Mvc;
using ORozdobudko;
using Web_cross_platform.Models;

namespace Web_cross_platform.Controllers
{
    public class LabsController : Controller
    {
        public IActionResult PR1()
        {
            return View();
        }

        [HttpPost]
        //[Authorize]
        public IActionResult PR1(CommonDataModel commonDataModel)
        {
            try
            {
                commonDataModel.Response = (Lab_1.Algoritm(Int32.Parse(commonDataModel.Data))).ToString();
                commonDataModel.Calculated = true;
            }
            catch (ArgumentException aex)
            {
                commonDataModel.ErrorValue = aex.Message;
            }
            catch (Exception ex)
            {
                commonDataModel.ErrorValue = ex.Message;
            }
            return View(commonDataModel);
        }

        public IActionResult PR2()
        {
            return View();
        }

        [HttpPost]
        //[Authorize]
        public IActionResult PR2(CommonDataModel commonDataModel)
        {
            try
            {
                commonDataModel.Response = (Lab_2.Algoritm(Int32.Parse(commonDataModel.Data))).ToString();
                commonDataModel.Calculated = true;
            }
            catch (ArgumentException aex)
            {
                commonDataModel.ErrorValue = aex.Message;
            }
            catch (Exception ex)
            {
                commonDataModel.ErrorValue = ex.Message;
            }
            return View(commonDataModel);
        }

        public IActionResult PR3()
        {
            return View();
        }

        [HttpPost]
        //[Authorize]
        public IActionResult PR3(CommonDataModel commonDataModel)
        {
            try
            {
                Lab_3 lab_3 = new Lab_3();
                lab_3.Algoritm(commonDataModel.Data);
                commonDataModel.Response = lab_3.Cycle == 0 ? "YES" : "NO";
                commonDataModel.Calculated = true;
            }
            catch (ArgumentException aex)
            {
                commonDataModel.ErrorValue = aex.Message;
            }
            catch (Exception ex)
            {
                commonDataModel.ErrorValue = ex.Message;
            }
            return View(commonDataModel);
        }
    }
}

Web_cross_platform/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Привіт</h1>
    <p>Проєкт розроблено з метою демонстрації лабораторних робіт студентом групи ІПЗ-41 Роздобудько Олександром(16 варіант).</p>
</div>

Web_cross_platform/Views/Labs/PR1.cshtml
@model Web_cross_platform.Models.CommonDataModel
@{
    ViewData["Title"] = "PR1";
}
<h1>@ViewData["Title"]</h1>


<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="PR1">
    <div class="form-group">
        <label for="pdata">Data</label>
        <input type="text" class="form-control" id="pdata" asp-for="Data">
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

@if (Model != null)
{
    <div class="container mt5">
        @if (Model.Calculated)
        {
            <div class="row">
                <label for="presponse">Response</label>
                <input type="text" id="presponse" value="@Model.Response">
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.ErrorValue))
        {
            <div class="row">
                <label for="perror"></label>
                <input type="text" id="perror" value="@Model.ErrorValue">
            </div>
        }
    </div>
}

Web_cross_platform/Views/Labs/PR2.cshtml
@model Web_cross_platform.Models.CommonDataModel
@{
    ViewData["Title"] = "PR2";
}
<h1>@ViewData["Title"]</h1>


<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="PR2">
    <div class="form-group">
        <label for="pdata">Data</label>
        <input type="text" class="form-control" id="pdata" asp-for="Data">
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

@if (Model != null)
{
    <div class="container mt5">
        @if (Model.Calculated)
        {
            <div class="row">
                <label for="presponse">Response</label>
                <input type="text" id="presponse" value="@Model.Response">
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.ErrorValue))
        {
            <div class="row">
                <label for="perror"></label>
                <input type="text" id="perror" value="@Model.ErrorValue">
            </div>
        }
    </div>
}

Web_cross_platform/Views/Labs/PR3.cshtml
@model Web_cross_platform.Models.CommonDataModel
@{
    ViewData["Title"] = "PR3";
}
<h1>@ViewData["Title"]</h1>


<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="PR3">
    <div class="form-outline">
        <label for="pdata">Data</label>
        <textarea class="form-control" id="pdata" rows="4" asp-for="Data"></textarea>
        <label class="form-label" for="pdata">Message</label>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

@if (Model != null)
{
    <div class="container mt5">
        @if (Model.Calculated)
        {
            <div class="row">
                <label for="presponse">Response</label>
                <input type="text" id="presponse" value="@Model.Response">
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.ErrorValue))
        {
            <div class="row">
                <label for="perror"></label>
                <input type="text" id="perror" value="@Model.ErrorValue">
            </div>
        }
    </div>
}

Web_cross_platform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_cross_platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_cross_platform.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web_cross_platform</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="PR1">PR1</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="PR2">PR2</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="PR3">PR3</a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><p class="navbar-text">Hello, @User.Identity.Name</p></li>
                            <li><a class="nav-link" asp-controller="Account" asp-action="Profile" id="profile-button">Profile</a></li>
                            <li>
                                <form class="form-inline" asp-controller="Account" asp-action="SignOut" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark" id="logout-button">Sign Out</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><a asp-controller="Account" asp-action="SignIn" id="login-button">Sign In</a></li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web_cross_platform - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>